name: Ubuntu
on: 
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
      - name: build lib
        run: make lib
        
