name: Ubuntu
on: 
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
      - name: build lib
        run: make lib
        
      - name: test
        run: make test
        
